name: exam_master
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  shamsi_date: ^1.0.1
  fl_chart: ^0.63.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.1.1
  uuid: ^4.0.0
  path_provider: ^2.1.4
  excel: ^2.0.0
  pdf: ^3.10.1
  printing: ^5.11.0
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^6.2.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.13.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: lib/assets/fonts/Vazirmatn-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Vazirmatn-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Vazirmatn-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Vazirmatn-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Vazirmatn-Black.ttf
          weight: 900
